[project]
name = "comfyui_danbooru_tags_upsampler"
description = "Makes the prompts for generating anime images more detailed by upsampling Danbooru tags."
version = "2.3.5"
license = {file = "LICENSE"}
requires-python = ">=3.10"
classifiers = [
    "Operating System :: OS Independent",
    "Environment :: GPU :: NVIDIA CUDA",
]

dependencies = [
    "transformers>=4.35.0",
    "optimum[onnxruntime]>=1.16.0",
    "tokenizers>=0.14.0",
    "sentencepiece"
]

[project.urls]
Repository = "https://github.com/rookiestar28/ComfyUI-Danbooru-Tags-Upsampler"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/rookiestar28/ComfyUI-Danbooru-Tags-Upsampler/wiki"
"Bug Tracker" = "https://github.com/rookiestar28/ComfyUI-Danbooru-Tags-Upsampler/issues"

[tool.comfy]
PublisherId = "rookiestar"
DisplayName = "ComfyUI Danbooru Tags Upsampler"
Icon = ""
includes = []
"requires-comfyui" = ">=0.22.3"
